name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        set -euo pipefail
        swift package clean
        swift build --sanitize="address"
        bash <(curl -s https://codecov.io/bash)
    - name: Run Tests
      run: |
        set -euo pipefail
        xcodebuild -scheme SoundsKit -enableAddressSanitizer YES test | xcpretty
    - name: Run tests
      run: swift test -v

