name: Build & Test

on:
  pull_request:
    branches: [ main ]
    
jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']

    steps:
      - uses: actions/checkout@v1
      - name: Show version
        run: swift --version
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test -v
