name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
          pwd
          set -euo pipefail
          swift package clean
          swift build --sanitize="address"
          bash <(curl -s https://codecov.io/bash)
      env: 
        destination: ${{ matrix.destination}}

    - name: Run Tests
      run: |
          set -euo pipefail
          xcodebuild -scheme AudioKit -enableAddressSanitizer YES test | xcpretty


