name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode_version }}.app
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
           pwd
           xcrun simctl list
           xcodebuild clean test -workspace SoundsKit.xcworkspace -scheme SoundsKit -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
           bash <(curl -s https://codecov.io/bash
      env: 
        destination: ${{ matrix.destination}}

    - name: Run tests
      run: swift test -v


