name: Swift

on:
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest
    strategy:
      matrix:
        destination: ['platform=iOS Simulator,OS=14.4,name=iPhone 12']
    env:
        DEVELOPER_DIR: /Applications/Xcode_12.app/Contents/Developer

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
           pwd
           set -o pipefail && env NSUnbufferedIO=YES xcodebuild build-for-testing -scheme SoundsKit -destination "platform=iOS Simulator,OS=latest,name=iPhone 12" | xcpretty
           bash <(curl -s https://codecov.io/bash)
      env: 
        destination: ${{ matrix.destination}}

    - name: Run tests
      run: swift test -v
