name: Build & Test

on:
  pull_request:
    branches: [ main ]
    
jobs:
  unit_tests:
    runs-on: macos-10.14
    steps:
    - name: Repository checkout
      uses: actions/checkout@v2
    - name: Build for macOS
      run: swift build -v
    - name: Run macOS tests
      run: swift test -v
   
